project:
  type: website

website:
  google-analytics: "G-MLL9M280YV"
  draft-mode: gone
  title: "The Curious Piper"
  description: "A blog about pipe smoking"
  site-url: https://www.thecuriouspiper.com
  open-graph: true
  twitter-card: true
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: YouTube
        href: https://www.youtube.com/@TheCuriousPiper
      - text: About
        href: about.qmd
    right:
      - icon: rss
        href: index.xml
  page-footer: 
    center: "Â© 2026 The Curious Piper"

format:
  html:
    theme:
      - litera
    include-after-body:
      - includes/title-banner-logo.html
    css: styles.css

