project:
  type: website
  resources:
    - assets/**

website:
  google-analytics: "G-MLL9M280YV"
  draft-mode: gone
  title: "The Curious Piper"
  description: "A blog about pipe smoking"
  site-url: https://www.thecuriouspiper.com
  open-graph: true
  twitter-card: true
  
  navbar:
    title: false
    left:
      - text: Home
        href: index.qmd
      - text: About
        href: about.qmd
      - text: YouTube
        href: https://www.youtube.com/@TheCuriousPiper
        target: _blank
        rel: noopener
      # - text: Instagram
      #   href: https://instagram.com
    right:
      - icon: youtube
        href: https://www.youtube.com/@TheCuriousPiper
        target: _blank
        rel: noopener
      - icon: rss
        href: index.xml

  page-footer: 
    center: "Â© 2026 The Curious Piper"
    right:
      - icon: youtube
        href: https://www.youtube.com/@TheCuriousPiper
        target: _blank
        rel: noopener
      # - icon: instagram
      #   href: https://instagram.com

format:
  html:
    theme: litera
    css: styles.css
    link-external-newwindow: true
    include-after-body:
      - _includes/after-header-logo.html
